linters-settings:
  gocyclo:
    min-complexity: 15
  goimports:
    local-prefixes: github.com/milligan22963/passphrase
  govet:
    check-shadowing: true
  misspell:
    locale: US
  nolintlint:
    allow-leading-space: false # require machine-readable nolint directives (with no leading space)
    allow-unused: false # report any unused nolint directives
    require-explanation: true # require an explanation for nolint directives
    require-specific: true # don't require nolint directives to be specific about which linter is being skipped
  revive:
    confidence: 0

linters:
  disable-all: true
  enable:
    - dogsled
    - errcheck
    - errorlint
    - exportloopref
    - funlen
    # - gochecknoinits
    - gocritic
    - goconst
    - gocyclo
    - gofumpt
    - goimports
    - revive
    - godox
    - gomnd
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - noctx
    - nolintlint
    - staticcheck
    - stylecheck
    - thelper
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace

issues:
  # enable issues excluded by default 
  exclude-use-default: false
  exclude-rules:
    - path: _test.go
      linters:
        - funlen
        - dupl